from datetime import datetime
from sqlalchemy import String, Float, Boolean, Text, DateTime, Integer
from sqlalchemy.orm import Mapped, mapped_column
from db import Base
class AppSettings(Base):
    __tablename__='app_settings'; id:Mapped[int]=mapped_column(Integer,primary_key=True,default=1); instant_booking:Mapped[bool]=mapped_column(Boolean,default=True); direct_discount_percent:Mapped[float]=mapped_column(Float,default=10); cleaning_fee:Mapped[float]=mapped_column(Float,default=220); tax_percent:Mapped[float]=mapped_column(Float,default=15); security_mode:Mapped[str]=mapped_column(String(40),default='authorization'); security_amount:Mapped[float]=mapped_column(Float,default=500); cancellation_policy:Mapped[str]=mapped_column(Text,default='Full refund up to 30 days before arrival; 50% refund up to 14 days before arrival; non-refundable inside 14 days.'); promo_code:Mapped[str]=mapped_column(String(50),default='RETURN10'); promo_percent:Mapped[float]=mapped_column(Float,default=10)
class ChatMessage(Base):
    __tablename__='chat_messages'; id:Mapped[int]=mapped_column(Integer,primary_key=True); name:Mapped[str]=mapped_column(String(120),default=''); email:Mapped[str]=mapped_column(String(180),default=''); message:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Customer(Base):
    __tablename__='customers'; id:Mapped[int]=mapped_column(Integer,primary_key=True); name:Mapped[str]=mapped_column(String(200)); email:Mapped[str]=mapped_column(String(200),unique=True); phone:Mapped[str]=mapped_column(String(40),default=''); address:Mapped[str]=mapped_column(Text,default=''); password_hash:Mapped[str]=mapped_column(String(255)); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class BookingRequest(Base):
    __tablename__='booking_requests'; id:Mapped[int]=mapped_column(Integer,primary_key=True); checkin:Mapped[str]=mapped_column(String(20)); checkout:Mapped[str]=mapped_column(String(20)); guests:Mapped[int]=mapped_column(Integer); guest_name:Mapped[str]=mapped_column(String(200),default=''); email:Mapped[str]=mapped_column(String(200),default=''); phone:Mapped[str]=mapped_column(String(40),default=''); address:Mapped[str]=mapped_column(Text,default=''); customer_id:Mapped[int|None]=mapped_column(Integer,nullable=True,default=None); total:Mapped[float]=mapped_column(Float,default=0); status:Mapped[str]=mapped_column(String(40),default='pending'); email_sent:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
