from datetime import datetime
from sqlalchemy import String, Float, Boolean, Text, DateTime, Integer
from sqlalchemy.orm import Mapped, mapped_column
from db import Base
class AppSettings(Base):
    __tablename__='app_settings'; id:Mapped[int]=mapped_column(Integer,primary_key=True,default=1); instant_booking:Mapped[bool]=mapped_column(Boolean,default=True); direct_discount_percent:Mapped[float]=mapped_column(Float,default=10); cleaning_fee:Mapped[float]=mapped_column(Float,default=220); tax_percent:Mapped[float]=mapped_column(Float,default=15); security_mode:Mapped[str]=mapped_column(String(40),default='authorization'); security_amount:Mapped[float]=mapped_column(Float,default=500); cancellation_policy:Mapped[str]=mapped_column(Text,default='Full refund up to 30 days before arrival; 50% refund up to 14 days before arrival; non-refundable inside 14 days.'); promo_code:Mapped[str]=mapped_column(String(50),default='RETURN10'); promo_percent:Mapped[float]=mapped_column(Float,default=10); airbnb_markup_percent:Mapped[float]=mapped_column(Float,default=17); vrbo_markup_percent:Mapped[float]=mapped_column(Float,default=20); booking_markup_percent:Mapped[float]=mapped_column(Float,default=25)
class ChatMessage(Base):
    __tablename__='chat_messages'; id:Mapped[int]=mapped_column(Integer,primary_key=True); name:Mapped[str]=mapped_column(String(120),default=''); email:Mapped[str]=mapped_column(String(180),default=''); message:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Customer(Base):
    __tablename__='customers'; id:Mapped[int]=mapped_column(Integer,primary_key=True); name:Mapped[str]=mapped_column(String(200)); email:Mapped[str]=mapped_column(String(200),unique=True); phone:Mapped[str]=mapped_column(String(40),default=''); address:Mapped[str]=mapped_column(Text,default=''); password_hash:Mapped[str]=mapped_column(String(255)); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class IcalReservation(Base):
    __tablename__='ical_reservations'; id:Mapped[int]=mapped_column(Integer,primary_key=True); uid:Mapped[str]=mapped_column(String(400),unique=True); platform:Mapped[str]=mapped_column(String(40)); checkin:Mapped[str]=mapped_column(String(20)); checkout:Mapped[str]=mapped_column(String(20)); guest_name:Mapped[str]=mapped_column(String(200),default=''); summary:Mapped[str]=mapped_column(String(500),default=''); raw_description:Mapped[str]=mapped_column(Text,default=''); notes:Mapped[str]=mapped_column(Text,default=''); is_new:Mapped[bool]=mapped_column(Boolean,default=True); synced_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class BookingRequest(Base):
    __tablename__='booking_requests'; id:Mapped[int]=mapped_column(Integer,primary_key=True); checkin:Mapped[str]=mapped_column(String(20)); checkout:Mapped[str]=mapped_column(String(20)); guests:Mapped[int]=mapped_column(Integer); guest_name:Mapped[str]=mapped_column(String(200),default=''); email:Mapped[str]=mapped_column(String(200),default=''); phone:Mapped[str]=mapped_column(String(40),default=''); address:Mapped[str]=mapped_column(Text,default=''); customer_id:Mapped[int|None]=mapped_column(Integer,nullable=True,default=None); total:Mapped[float]=mapped_column(Float,default=0); status:Mapped[str]=mapped_column(String(40),default='pending'); email_sent:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Task(Base):
    __tablename__='tasks'; id:Mapped[int]=mapped_column(Integer,primary_key=True); title:Mapped[str]=mapped_column(String(200)); category:Mapped[str]=mapped_column(String(40),default='cleaning'); status:Mapped[str]=mapped_column(String(20),default='pending'); priority:Mapped[str]=mapped_column(String(20),default='normal'); assigned_to:Mapped[str]=mapped_column(String(100),default=''); notes:Mapped[str]=mapped_column(Text,default=''); due_date:Mapped[str]=mapped_column(String(20),default=''); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); completed_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True,default=None)
class Expense(Base):
    __tablename__='expenses'; id:Mapped[int]=mapped_column(Integer,primary_key=True); date:Mapped[str]=mapped_column(String(20)); category:Mapped[str]=mapped_column(String(60)); description:Mapped[str]=mapped_column(String(300)); amount:Mapped[float]=mapped_column(Float); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class GuestReview(Base):
    __tablename__='guest_reviews'; id:Mapped[int]=mapped_column(Integer,primary_key=True); platform:Mapped[str]=mapped_column(String(40)); guest_name:Mapped[str]=mapped_column(String(200),default=''); rating:Mapped[float]=mapped_column(Float); review_text:Mapped[str]=mapped_column(Text,default=''); response:Mapped[str]=mapped_column(Text,default=''); review_date:Mapped[str]=mapped_column(String(20)); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class AutoMessage(Base):
    __tablename__='auto_messages'; id:Mapped[int]=mapped_column(Integer,primary_key=True); name:Mapped[str]=mapped_column(String(100)); trigger:Mapped[str]=mapped_column(String(40)); send_hours:Mapped[int]=mapped_column(Integer,default=0); subject:Mapped[str]=mapped_column(String(200),default=''); body:Mapped[str]=mapped_column(Text); enabled:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class PropertyInfo(Base):
    __tablename__='property_info'; id:Mapped[int]=mapped_column(Integer,primary_key=True,default=1); wifi_name:Mapped[str]=mapped_column(String(200),default=''); wifi_password:Mapped[str]=mapped_column(String(200),default=''); door_code:Mapped[str]=mapped_column(String(100),default=''); parking_info:Mapped[str]=mapped_column(Text,default=''); checkin_instructions:Mapped[str]=mapped_column(Text,default=''); checkout_instructions:Mapped[str]=mapped_column(Text,default=''); house_rules:Mapped[str]=mapped_column(Text,default=''); emergency_contacts:Mapped[str]=mapped_column(Text,default=''); trash_info:Mapped[str]=mapped_column(Text,default=''); pool_info:Mapped[str]=mapped_column(Text,default=''); thermostat_info:Mapped[str]=mapped_column(Text,default=''); extra_notes:Mapped[str]=mapped_column(Text,default='')
class DailyPrice(Base):
    __tablename__='daily_prices'; date:Mapped[str]=mapped_column(String(10),primary_key=True); price:Mapped[float]=mapped_column(Float,default=0); min_stay:Mapped[int]=mapped_column(Integer,default=1); demand_color:Mapped[str]=mapped_column(String(20),default=''); occupancy:Mapped[int]=mapped_column(Integer,default=0); synced_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
